discord:
  token: "" # discord bot token
  guild_id: "" # target guild id
  webhook_url: "" # discord webhook url
  channels:
    chat_id: "" # target channel id
    srv_id: "" # SRV logging not working

settings:
  custom_message: true # minecraft join quit message setting
  activity:
    enable: true
    context: "Minecord" # activity string
  srv:
    enable: false # not working
  style: 0

format:
  enable: "ğŸ ì„œë²„ê°€ í™œì„±í™” ë˜ì—ˆì–´ìš”"
  disable: "ğŸ›‘ ì„œë²„ê°€ ë¹„í™œì„±í™” ë˜ì—ˆì–´ìš”"
  online: "í˜„ì¬ ì„œë²„ì— ì‚¬ëŒì´ ì—†ì–´ìš”"
  channel: "ì„¤ì •ëœ ì±„ë„ì—ì„œë§Œ ì´ ëª…ë ¹ì–´ë¥¼ ì‚¬ìš©í•˜ì‹¤ ìˆ˜ ìˆì–´ìš”"
  error: "ëª…ë ¹ì–´ ì‹¤í–‰ ë„ì¤‘ì— ì˜¤ë¥˜ê°€ ë°œìƒ í–ˆì–´ìš”"
  chat:
    mc: "{aqua}{user}{reset}: {context}"
    discord: "{user}: {context}"
  player:
    join: "{user}ë‹˜ì´ ê²Œì„ì— ì ‘ì†í–ˆì–´ìš”. {online}/{max}ëª…"
    quit: "{user}ë‹˜ì´ ê²Œì„ì—ì„œ ë‚˜ê°”ì–´ìš”. {online}/{max}ëª…"
    death: "{user}ë‹˜ì´ ì‚¬ë§ í•˜ì…¨ì–´ìš”"
    advancement: "{user}ë‹˜ì´ {advancement}ì„(ë¥¼) í´ë¦¬ì–´ í•˜ì…¨ì–´ìš”"
    kick: "{user}ë‹˜ì´ ì¶”ë°© ë˜ì—ˆì–´ìš”"

color:
  default: 0x77C4A3
  join: 0x00DD00
  quit: 0xDD0000
  death: 0x3E3E3E
  kick: 0x2D2D2D